# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('bin_id', models.IntegerField()),
                ('gw_id', models.IntegerField()),
            ],
        ),
    ]
